# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.CharField(max_length=45),
        ),
    ]
