# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.authors'),
        ),
    ]
