# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0007_auto_20190915_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='This is a description', editable=False),
        ),
    ]
