# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
